apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  use-forwarded-headers: "true"
  # Inne opcje konfiguracji NGINX mogą być dodane tutaj
